alter table service_settings drop foreign key FK10e3oo4ayc3q32mx23hd3jgbx;
alter table service_settings_weather_settings drop foreign key FKg362n3168d7q4tudfwkhfs9j6;
alter table service_settings_weather_settings drop foreign key FKq22q6odoieqjwwu8mtu59hm81;
alter table telegram_chat drop foreign key FKkska79uqrjtucfn1mb6cf75pl;
alter table telegram_contact drop foreign key FKdaxv9k3mc2yicbcl9n0scdjpr;
alter table telegram_location drop foreign key FK5xrp8uk60lqyhhft6q4a7qcsv;
alter table telegram_location drop foreign key FKs1luk51oyf6gquy6ffoo2ipit;
alter table telegram_message drop foreign key FK4x1qb0neggq6wpi3whluai96p;
alter table telegram_message drop foreign key FKcm3itqjvfgbft5m8pewkr0w5u;
alter table telegram_message drop foreign key FKd5xty33xcb3fdlc2c98iu6v59;
alter table telegram_message drop foreign key FKa8ijvujygr3mjw6mhssy65n6l;
alter table telegram_update drop foreign key FK9v8wv5gaap69ww8uen255epco;
alter table users drop foreign key FK6e6jju56d6pfjl5tshyx1a264;
alter table users drop foreign key FKl1biaaq30akls6dg9op67h786;
alter table weather drop foreign key FKf75wr0ucmidk90evh96uekk34;
alter table weather drop foreign key FKg0cue5ghqonhya1dmkeo16gmg;
alter table weather_forecast_hours drop foreign key FK3d56pbc545h4gskgvhiljllaq;
alter table weather_forecast_hours drop foreign key FKsu1qfxd4iguli3rmjcbfvy4tc;
alter table weather_forecast_parts drop foreign key FK1xeyd7k1psd89cgudq0bxkjfd;
alter table weather_forecast_parts drop foreign key FKmngkjeq76qcm9pt89hgqaly09;
alter table weather_forecasts drop foreign key FKyjjciytbwhnhv5kqmieitypc;
alter table weather_forecasts drop foreign key FKr8iid0q9v5bh0sw94j776cud2;
alter table weather_info drop foreign key FKn1ryb0fdikfthprqhrsof2x7r;
alter table weather_settings drop foreign key FKk9ugjmsb8cx22wrrpvutklnd2;
alter table weather_settings drop foreign key FKmm4092k2cv3wka1ftijivbkdp;
drop table if exists hibernate_sequence;
drop table if exists service_settings;
drop table if exists service_settings_weather_settings;
drop table if exists telegram_chat;
drop table if exists telegram_contact;
drop table if exists telegram_location;
drop table if exists telegram_message;
drop table if exists telegram_update;
drop table if exists users;
drop table if exists weather;
drop table if exists weather_fact;
drop table if exists weather_forecast;
drop table if exists weather_forecast_hours;
drop table if exists weather_forecast_parts;
drop table if exists weather_forecasts;
drop table if exists weather_hour;
drop table if exists weather_info;
drop table if exists weather_part;
drop table if exists weather_tz_info;
drop table if exists weather_settings;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table service_settings (id bigint not null, active bit, count_of_notification integer, service integer, user_id integer, primary key (id)) engine=InnoDB;
create table service_settings_weather_settings (service_settings_id bigint not null, weather_settings_id bigint not null) engine=InnoDB;
create table telegram_chat (id bigint not null, creation_date datetime(6), channel_chat bit, group_chat bit, super_group_chat bit, user_chat bit, user_id integer, primary key (id)) engine=InnoDB;
create table telegram_contact (id integer not null, creation_date datetime(6), first_name varchar(255), last_name varchar(255), phone_number varchar(255), user_id integer, primary key (id)) engine=InnoDB;
create table telegram_location (id bigint not null, creation_date datetime(6), city varchar(255), latitude float, longitude float, tz_info_id bigint, user_id integer, primary key (id)) engine=InnoDB;
create table telegram_message (id integer not null, creation_date datetime(6), text varchar(255), chat_id bigint, contact_id integer, from_id integer, location_id bigint, primary key (id)) engine=InnoDB;
create table telegram_update (id integer not null, creation_date datetime(6), message_id integer, primary key (id)) engine=InnoDB;
create table users (id integer not null, creation_date datetime(6), bot bit, email varchar(255), first_name varchar(255), language_code varchar(255), last_name varchar(255), phone varchar(255), registered bit, status integer, user_name varchar(255), location_id bigint, tz_info_id bigint, primary key (id)) engine=InnoDB;
create table weather (id bigint not null, now float not null, now_date_time varchar(255), fact_id bigint, info_id bigint, primary key (id)) engine=InnoDB;
create table weather_fact (id bigint not null, cloudness float, daytime varchar(255), feels_like float, humidity float, icon varchar(255), obs_time float, polar bit, prec_strength float, prec_type float, pressure_mm float, pressure_pa float, season varchar(255), temp float, temp_water float, weather_condition varchar(255), wind_dir varchar(255), wind_gust float, wind_speed float, primary key (id)) engine=InnoDB;
create table weather_forecast (id bigint not null, date varchar(255), date_ts float, moon_code integer, moon_text varchar(255), sunrise varchar(255), sunset varchar(255), week float, primary key (id)) engine=InnoDB;
create table weather_forecast_hours (yandex_weather_forecast_id bigint not null, hours_id bigint not null) engine=InnoDB;
create table weather_forecast_parts (yandex_weather_forecast_id bigint not null, parts_id bigint not null) engine=InnoDB;
create table weather_forecasts (yandex_weather_id bigint not null, forecasts_id bigint not null) engine=InnoDB;
create table weather_hour (id bigint not null, cloudness float, feels_like float, hour varchar(255), hour_ts float, humidity float, icon varchar(255), prec_mm float, prec_period float, prec_strength float, prec_type float, pressure_mm float, pressure_pa float, temp float, weather_condition varchar(255), wind_dir varchar(255), wind_gust float, wind_speed float, primary key (id)) engine=InnoDB;
create table weather_info (id bigint not null, def_pressure_mm float, def_pressure_pa float, lat float, lon float, url varchar(255), tz_info_id bigint, primary key (id)) engine=InnoDB;
create table weather_part (id bigint not null, cloudness float, daytime varchar(255), feels_like float, humidity float, icon varchar(255), name varchar(255), polar bit, prec_mm float, prec_period float, prec_strength float, prec_type float, pressure_mm float, pressure_pa float, source varchar(255), temp_avg float, temp_max float, temp_min float, weather_condition varchar(255), wind_dir varchar(255), wind_gust float, wind_speed float, primary key (id)) engine=InnoDB;
create table weather_tz_info (id bigint not null, abbr varchar(255), dst bit, name varchar(255), offset float, primary key (id)) engine=InnoDB;
create table weather_settings (id bigint not null, city varchar(255), latitude float not null, longitude float not null, service_settings_id bigint, user_id integer, primary key (id)) engine=InnoDB;
alter table service_settings_weather_settings add constraint UK_g3xl0y3nvbwv1nk22061vyp9 unique (weather_settings_id);
alter table weather_forecast_hours add constraint UK_s6lkmf5t2t01pexbtx3tysesi unique (hours_id);
alter table weather_forecast_parts add constraint UK_n6oikv0nlus8c3o1k54rv5hrm unique (parts_id);
alter table weather_forecasts add constraint UK_3l6udtou19rhnexsf554c9uq3 unique (forecasts_id);
alter table service_settings add constraint FK10e3oo4ayc3q32mx23hd3jgbx foreign key (user_id) references users (id);
alter table service_settings_weather_settings add constraint FKg362n3168d7q4tudfwkhfs9j6 foreign key (weather_settings_id) references weather_settings (id);
alter table service_settings_weather_settings add constraint FKq22q6odoieqjwwu8mtu59hm81 foreign key (service_settings_id) references service_settings (id);
alter table telegram_chat add constraint FKkska79uqrjtucfn1mb6cf75pl foreign key (user_id) references users (id);
alter table telegram_contact add constraint FKdaxv9k3mc2yicbcl9n0scdjpr foreign key (user_id) references users (id);
alter table telegram_location add constraint FK5xrp8uk60lqyhhft6q4a7qcsv foreign key (tz_info_id) references weather_tz_info (id);
alter table telegram_location add constraint FKs1luk51oyf6gquy6ffoo2ipit foreign key (user_id) references users (id);
alter table telegram_message add constraint FK4x1qb0neggq6wpi3whluai96p foreign key (chat_id) references telegram_chat (id);
alter table telegram_message add constraint FKcm3itqjvfgbft5m8pewkr0w5u foreign key (contact_id) references telegram_contact (id);
alter table telegram_message add constraint FKd5xty33xcb3fdlc2c98iu6v59 foreign key (from_id) references users (id);
alter table telegram_message add constraint FKa8ijvujygr3mjw6mhssy65n6l foreign key (location_id) references telegram_location (id);
alter table telegram_update add constraint FK9v8wv5gaap69ww8uen255epco foreign key (message_id) references telegram_message (id);
alter table users add constraint FK6e6jju56d6pfjl5tshyx1a264 foreign key (location_id) references telegram_location (id);
alter table users add constraint FKl1biaaq30akls6dg9op67h786 foreign key (tz_info_id) references weather_tz_info (id);
alter table weather add constraint FKf75wr0ucmidk90evh96uekk34 foreign key (fact_id) references weather_fact (id);
alter table weather add constraint FKg0cue5ghqonhya1dmkeo16gmg foreign key (info_id) references weather_info (id);
alter table weather_forecast_hours add constraint FK3d56pbc545h4gskgvhiljllaq foreign key (hours_id) references weather_hour (id);
alter table weather_forecast_hours add constraint FKsu1qfxd4iguli3rmjcbfvy4tc foreign key (yandex_weather_forecast_id) references weather_forecast (id);
alter table weather_forecast_parts add constraint FK1xeyd7k1psd89cgudq0bxkjfd foreign key (parts_id) references weather_part (id);
alter table weather_forecast_parts add constraint FKmngkjeq76qcm9pt89hgqaly09 foreign key (yandex_weather_forecast_id) references weather_forecast (id);
alter table weather_forecasts add constraint FKyjjciytbwhnhv5kqmieitypc foreign key (forecasts_id) references weather_forecast (id);
alter table weather_forecasts add constraint FKr8iid0q9v5bh0sw94j776cud2 foreign key (yandex_weather_id) references weather (id);
alter table weather_info add constraint FKn1ryb0fdikfthprqhrsof2x7r foreign key (tz_info_id) references weather_tz_info (id);
alter table weather_settings add constraint FKk9ugjmsb8cx22wrrpvutklnd2 foreign key (service_settings_id) references service_settings (id);
alter table weather_settings add constraint FKmm4092k2cv3wka1ftijivbkdp foreign key (user_id) references users (id);