create table news_category (id bigint not null auto_increment, creation_date datetime(6), name varchar(255), primary key (id)) engine=InnoDB;
create table news_item (id bigint not null auto_increment, author varchar(255), count_of_viewers integer, creation_date datetime(6), description varchar(1024), link varchar(255), photo_url varchar(255), publication_date datetime(6), title varchar(255), uri varchar(255), source_id bigint, primary key (id)) engine=InnoDB;
create table news_item_category_list (news_item_id bigint not null, category_list_id bigint not null) engine=InnoDB;
create table news_settings (id bigint not null auto_increment, is_active_user_settings bit not null, last_news_publication_date datetime(6), last_viewed_news_item_id bigint, notification_service_settings_id bigint, user_id integer, primary key (id)) engine=InnoDB;
create table news_settings_news_categories (news_settings_id bigint not null, news_categories_id bigint not null, primary key (news_settings_id, news_categories_id)) engine=InnoDB;
create table news_settings_news_sources (news_settings_id bigint not null, news_sources_id bigint not null, primary key (news_settings_id, news_sources_id)) engine=InnoDB;
create table news_settings_viewed_news (news_settings_id bigint not null, viewed_news_id bigint not null, primary key (news_settings_id, viewed_news_id)) engine=InnoDB;
create table news_source (id bigint not null auto_increment, creation_date datetime(6), last_update datetime(6), link varchar(255), logo_image_url varchar(255), name varchar(255), source_name varchar(255), primary key (id)) engine=InnoDB;
create table notification_service_settings (id bigint not null auto_increment, active bit, count_of_notification_per_day integer, last_notification datetime(6), notification_interval float, service_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table notification_service_settings_news_settings (notification_service_settings_id bigint not null, news_settings_id bigint not null) engine=InnoDB;
create table notification_service_settings_twitter_settings (notification_service_settings_id bigint not null, twitter_settings_id bigint not null) engine=InnoDB;
create table notification_service_settings_weather_settings (notification_service_settings_id bigint not null, weather_settings_id bigint not null) engine=InnoDB;
create table telegram_chat (id bigint not null, creation_date datetime(6), channel_chat bit, group_chat bit, super_group_chat bit, user_chat bit, user_id integer, primary key (id)) engine=InnoDB;
create table telegram_contact (id integer not null, creation_date datetime(6), first_name varchar(255), last_name varchar(255), phone_number varchar(255), user_id integer, primary key (id)) engine=InnoDB;
create table telegram_location (id bigint not null auto_increment, creation_date datetime(6), city varchar(255), latitude float, longitude float, tz_info_id bigint, user_id integer, primary key (id)) engine=InnoDB;
create table telegram_message (id integer not null, creation_date datetime(6), text varchar(255), chat_id bigint, contact_id integer, user_id integer, location_id bigint, primary key (id)) engine=InnoDB;
create table telegram_update (id integer not null, creation_date datetime(6), message_id integer, primary key (id)) engine=InnoDB;
create table tweet (id bigint not null, created_at datetime(6), favorite_count integer, from_user varchar(255), from_user_id bigint, id_str varchar(255), link varchar(255), profile_image_url varchar(255), retweet_count integer, text varchar(300), to_user_id bigint, hashtag_id bigint, nickname_id bigint, primary key (id)) engine=InnoDB;
create table twitter_hashtag (id bigint not null auto_increment, creation_date datetime(6), hashtag varchar(255), primary key (id)) engine=InnoDB;
create table twitter_people (id bigint not null auto_increment, creation_date datetime(6), nickname varchar(255), primary key (id)) engine=InnoDB;
create table twitter_settings (id bigint not null auto_increment, is_active_user_settings bit not null, last_tweet_creation_date datetime(6), last_viewed_tweet_id bigint, notification_service_settings_id bigint, user_id integer, primary key (id)) engine=InnoDB;
create table twitter_settings_twitter_hashtags (twitter_settings_id bigint not null, twitter_hashtags_id bigint not null, primary key (twitter_settings_id, twitter_hashtags_id)) engine=InnoDB;
create table twitter_settings_twitter_people (twitter_settings_id bigint not null, twitter_people_id bigint not null, primary key (twitter_settings_id, twitter_people_id)) engine=InnoDB;
create table twitter_settings_viewed_tweets (twitter_settings_id bigint not null, viewed_tweets_id bigint not null, primary key (twitter_settings_id, viewed_tweets_id)) engine=InnoDB;
create table users (id integer not null, creation_date datetime(6), bot bit, email varchar(255), first_name varchar(255), language_code varchar(255), last_name varchar(255), phone varchar(255), registered bit, status integer, user_name varchar(255), location_id bigint, tz_info_id bigint, primary key (id)) engine=InnoDB;
create table weather (id bigint not null auto_increment, now float not null, now_date_time varchar(255), fact_id bigint, info_id bigint, primary key (id)) engine=InnoDB;
create table weather_fact (id bigint not null auto_increment, cloudness float, daytime varchar(255), feels_like float, humidity float, icon varchar(255), obs_time float, polar bit, prec_strength float, prec_type float, pressure_mm float, pressure_pa float, season varchar(255), temp float, temp_water float, weather_condition varchar(255), wind_dir varchar(255), wind_gust float, wind_speed float, primary key (id)) engine=InnoDB;
create table weather_forecast (id bigint not null auto_increment, date varchar(255), date_ts float, moon_code integer, moon_text varchar(255), sunrise varchar(255), sunset varchar(255), week float, primary key (id)) engine=InnoDB;
create table weather_forecast_hours (yandex_weather_forecast_id bigint not null, hours_id bigint not null) engine=InnoDB;
create table weather_forecast_parts (yandex_weather_forecast_id bigint not null, parts_id bigint not null) engine=InnoDB;
create table weather_forecasts (yandex_weather_id bigint not null, forecasts_id bigint not null) engine=InnoDB;
create table weather_hour (id bigint not null auto_increment, cloudness float, feels_like float, hour varchar(255), hour_ts float, humidity float, icon varchar(255), prec_mm float, prec_period float, prec_strength float, prec_type float, pressure_mm float, pressure_pa float, temp float, weather_condition varchar(255), wind_dir varchar(255), wind_gust float, wind_speed float, primary key (id)) engine=InnoDB;
create table weather_info (id bigint not null auto_increment, def_pressure_mm float, def_pressure_pa float, lat float, lon float, url varchar(255), tz_info_id bigint, primary key (id)) engine=InnoDB;
create table weather_part (id bigint not null auto_increment, cloudness float, daytime varchar(255), feels_like float, humidity float, icon varchar(255), name varchar(255), polar bit, prec_mm float, prec_period float, prec_strength float, prec_type float, pressure_mm float, pressure_pa float, source varchar(255), temp_avg float, temp_max float, temp_min float, weather_condition varchar(255), wind_dir varchar(255), wind_gust float, wind_speed float, primary key (id)) engine=InnoDB;
create table weather_tz_info (id bigint not null auto_increment, abbr varchar(255), dst bit, name varchar(255), offset float, primary key (id)) engine=InnoDB;
create table weather_city (id bigint not null auto_increment, creation_date datetime(6), latitude float not null, longitude float not null, name varchar(255), primary key (id)) engine=InnoDB;
create table weather_settings (id bigint not null auto_increment, last_city_creation_date datetime(6), last_viewed_weather_city_id bigint, notification_service_settings_id bigint, user_id integer, primary key (id)) engine=InnoDB;
create table weather_settings_cities (weather_settings_id bigint not null, cities_id bigint not null, primary key (weather_settings_id, cities_id)) engine=InnoDB;
create table weather_settings_viewed_cities (weather_settings_id bigint not null, viewed_cities_id bigint not null, primary key (weather_settings_id, viewed_cities_id)) engine=InnoDB;
create index news_category_name_index on news_category (name);
create index news_item_uri_index on news_item (uri);
create index news_settings_user_id_index on news_settings (user_id);
alter table news_settings_news_categories drop index UK_qbp0yx9jkclwkx5bcbpm9ow0b;
alter table news_settings_news_categories add constraint UK_qbp0yx9jkclwkx5bcbpm9ow0b unique (news_categories_id);
alter table news_settings_news_sources drop index UK_awul8jgyim3b7t570sy6842e;
alter table news_settings_news_sources add constraint UK_awul8jgyim3b7t570sy6842e unique (news_sources_id);
alter table news_settings_viewed_news drop index UK_2a4iaanceualseb1mlk8efcon;
alter table news_settings_viewed_news add constraint UK_2a4iaanceualseb1mlk8efcon unique (viewed_news_id);
create index news_source_source_name_index on news_source (source_name);
create index news_source_name_index on news_source (name);
create index notification_settings_user_id_index on notification_service_settings (user_id);
create index notification_settings_service_id_index on notification_service_settings (service_id);
create index notification_settings_active_index on notification_service_settings (active);
create index notification_settings_count_of_notification_per_day_index on notification_service_settings (count_of_notification_per_day);
alter table notification_service_settings_news_settings drop index UK_ha4vu2b3gga8f4hm7ra6mi71d;
alter table notification_service_settings_news_settings add constraint UK_ha4vu2b3gga8f4hm7ra6mi71d unique (news_settings_id);
alter table notification_service_settings_twitter_settings drop index UK_dr7quilvq34qdhowltig46lqx;
alter table notification_service_settings_twitter_settings add constraint UK_dr7quilvq34qdhowltig46lqx unique (twitter_settings_id);
alter table notification_service_settings_weather_settings drop index UK_jdspwkvmr9pn5tx9yxerblr3i;
alter table notification_service_settings_weather_settings add constraint UK_jdspwkvmr9pn5tx9yxerblr3i unique (weather_settings_id);
create index chat_user_id_index on telegram_chat (user_id);
create index contact_user_id_index on telegram_contact (user_id);
create index location_user_id_index on telegram_location (user_id);
create index location_longitude_index on telegram_location (longitude);
create index location_latitude_index on telegram_location (latitude);
create index message_chat_id_index on telegram_message (chat_id);
create index message_user_id_index on telegram_message (user_id);
create index update_message_id_index on telegram_update (message_id);
create index twitter_settings_user_id_index on twitter_settings (user_id);
alter table twitter_settings_twitter_hashtags drop index UK_iklstxfsckqamw51rkgccwr6r;
alter table twitter_settings_twitter_hashtags add constraint UK_iklstxfsckqamw51rkgccwr6r unique (twitter_hashtags_id);
alter table twitter_settings_twitter_people drop index UK_r69512wxttpvxiqq8a3ovbjxr;
alter table twitter_settings_twitter_people add constraint UK_r69512wxttpvxiqq8a3ovbjxr unique (twitter_people_id);
alter table twitter_settings_viewed_tweets drop index UK_37kgl2osajfgc8642r3sntnyn;
alter table twitter_settings_viewed_tweets add constraint UK_37kgl2osajfgc8642r3sntnyn unique (viewed_tweets_id);
alter table weather_forecast_hours drop index UK_s6lkmf5t2t01pexbtx3tysesi;
alter table weather_forecast_hours add constraint UK_s6lkmf5t2t01pexbtx3tysesi unique (hours_id);
alter table weather_forecast_parts drop index UK_n6oikv0nlus8c3o1k54rv5hrm;
alter table weather_forecast_parts add constraint UK_n6oikv0nlus8c3o1k54rv5hrm unique (parts_id);
alter table weather_forecasts drop index UK_3l6udtou19rhnexsf554c9uq3;
alter table weather_forecasts add constraint UK_3l6udtou19rhnexsf554c9uq3 unique (forecasts_id);
create index weather_settings_user_id_index on weather_settings (user_id);
alter table weather_settings_cities drop index UK_dod17myv440dshojvxvmv5rg4;
alter table weather_settings_cities add constraint UK_dod17myv440dshojvxvmv5rg4 unique (cities_id);
alter table weather_settings_viewed_cities drop index UK_npsj17055tmgmdava11nqpg2j;
alter table weather_settings_viewed_cities add constraint UK_npsj17055tmgmdava11nqpg2j unique (viewed_cities_id);
alter table news_item add constraint FKgvfqgjvjwfnjfn0p7xbviy5rt foreign key (source_id) references news_source (id);
alter table news_item_category_list add constraint FK87c1risc5v6ursiqb2wcrp3i4 foreign key (category_list_id) references news_category (id);
alter table news_item_category_list add constraint FKdhedsl0p0ffmloua87i6x9ph2 foreign key (news_item_id) references news_item (id);
alter table news_settings add constraint FK88q0obsk5lwtb4bp2d7dptkdm foreign key (last_viewed_news_item_id) references news_item (id);
alter table news_settings add constraint FKlt34y45djljik0r55xo0i0v0u foreign key (notification_service_settings_id) references notification_service_settings (id);
alter table news_settings add constraint FKcbtdfqkjpvv43nxh49v3b5gkt foreign key (user_id) references users (id);
alter table news_settings_news_categories add constraint FKl4c6oxdkj6a3qyajy2ly3txbo foreign key (news_categories_id) references news_category (id);
alter table news_settings_news_categories add constraint FK7kis4wn4d4fygl0wkkew8lw8f foreign key (news_settings_id) references news_settings (id);
alter table news_settings_news_sources add constraint FKg2p4wki4el1fd33nkubeea0nj foreign key (news_sources_id) references news_source (id);
alter table news_settings_news_sources add constraint FKrra3yylxmq6y12ucbea9plrsc foreign key (news_settings_id) references news_settings (id);
alter table news_settings_viewed_news add constraint FKp443rdimpjpymcn1fmgl82pfo foreign key (viewed_news_id) references news_item (id);
alter table news_settings_viewed_news add constraint FK8ha9bh8s37p3e0257lii77te6 foreign key (news_settings_id) references news_settings (id);
alter table notification_service_settings add constraint FKbuadjj0m06hy742ifoo1cp8rg foreign key (user_id) references users (id);
alter table notification_service_settings_news_settings add constraint FKenxu0s6wroyu1tc2eays5hhnv foreign key (news_settings_id) references news_settings (id);
alter table notification_service_settings_news_settings add constraint FK6qm0qhxad1141opvli6ffexgl foreign key (notification_service_settings_id) references notification_service_settings (id);
alter table notification_service_settings_twitter_settings add constraint FKao7bt5dydy6tpxs1xhmewve2x foreign key (twitter_settings_id) references twitter_settings (id);
alter table notification_service_settings_twitter_settings add constraint FKpufe3huq23a7eh5iudtkvmlfm foreign key (notification_service_settings_id) references notification_service_settings (id);
alter table notification_service_settings_weather_settings add constraint FKal8fm2ic85m5qdyxsfvxrebe9 foreign key (weather_settings_id) references weather_settings (id);
alter table notification_service_settings_weather_settings add constraint FKqi77hdktq24vgwoy2uxxswxxn foreign key (notification_service_settings_id) references notification_service_settings (id);
alter table telegram_chat add constraint FKkska79uqrjtucfn1mb6cf75pl foreign key (user_id) references users (id);
alter table telegram_contact add constraint FKdaxv9k3mc2yicbcl9n0scdjpr foreign key (user_id) references users (id);
alter table telegram_location add constraint FK5xrp8uk60lqyhhft6q4a7qcsv foreign key (tz_info_id) references weather_tz_info (id);
alter table telegram_location add constraint FKs1luk51oyf6gquy6ffoo2ipit foreign key (user_id) references users (id);
alter table telegram_message add constraint FK4x1qb0neggq6wpi3whluai96p foreign key (chat_id) references telegram_chat (id);
alter table telegram_message add constraint FKcm3itqjvfgbft5m8pewkr0w5u foreign key (contact_id) references telegram_contact (id);
alter table telegram_message add constraint FK34eugihce50josndnipgtd8n8 foreign key (user_id) references users (id);
alter table telegram_message add constraint FKa8ijvujygr3mjw6mhssy65n6l foreign key (location_id) references telegram_location (id);
alter table telegram_update add constraint FK9v8wv5gaap69ww8uen255epco foreign key (message_id) references telegram_message (id);
alter table tweet add constraint FKin5gaxw2ub4at9qqa4wqv7677 foreign key (hashtag_id) references twitter_hashtag (id);
alter table tweet add constraint FK10hr78uu5yaf9r2xr3tcbfnct foreign key (nickname_id) references twitter_people (id);
alter table twitter_settings add constraint FK8oeubi59ykada0hl003klfvdk foreign key (last_viewed_tweet_id) references tweet (id);
alter table twitter_settings add constraint FKrmi1ndbbo71i2al6xrymta4wj foreign key (notification_service_settings_id) references notification_service_settings (id);
alter table twitter_settings add constraint FK5cgb5w8ydu1rp61rn879ih1a9 foreign key (user_id) references users (id);
alter table twitter_settings_twitter_hashtags add constraint FKiyt9fqim3b42tolvudqp1l6pc foreign key (twitter_hashtags_id) references twitter_hashtag (id);
alter table twitter_settings_twitter_hashtags add constraint FKfwp48pu0obf7biih944kgy936 foreign key (twitter_settings_id) references twitter_settings (id);
alter table twitter_settings_twitter_people add constraint FKh46jkahsf6wdmc2gp81kqsxpa foreign key (twitter_people_id) references twitter_people (id);
alter table twitter_settings_twitter_people add constraint FKm1qsb1lw9w8wx085l05m9r2r1 foreign key (twitter_settings_id) references twitter_settings (id);
alter table twitter_settings_viewed_tweets add constraint FK986lutgxufss7hecdxbv1ln00 foreign key (viewed_tweets_id) references tweet (id);
alter table twitter_settings_viewed_tweets add constraint FK7od1f630xlp7ha0sy3ngtghxq foreign key (twitter_settings_id) references twitter_settings (id);
alter table users add constraint FK6e6jju56d6pfjl5tshyx1a264 foreign key (location_id) references telegram_location (id);
alter table users add constraint FKl1biaaq30akls6dg9op67h786 foreign key (tz_info_id) references weather_tz_info (id);
alter table weather add constraint FKf75wr0ucmidk90evh96uekk34 foreign key (fact_id) references weather_fact (id);
alter table weather add constraint FKg0cue5ghqonhya1dmkeo16gmg foreign key (info_id) references weather_info (id);
alter table weather_forecast_hours add constraint FK3d56pbc545h4gskgvhiljllaq foreign key (hours_id) references weather_hour (id);
alter table weather_forecast_hours add constraint FKsu1qfxd4iguli3rmjcbfvy4tc foreign key (yandex_weather_forecast_id) references weather_forecast (id);
alter table weather_forecast_parts add constraint FK1xeyd7k1psd89cgudq0bxkjfd foreign key (parts_id) references weather_part (id);
alter table weather_forecast_parts add constraint FKmngkjeq76qcm9pt89hgqaly09 foreign key (yandex_weather_forecast_id) references weather_forecast (id);
alter table weather_forecasts add constraint FKyjjciytbwhnhv5kqmieitypc foreign key (forecasts_id) references weather_forecast (id);
alter table weather_forecasts add constraint FKr8iid0q9v5bh0sw94j776cud2 foreign key (yandex_weather_id) references weather (id);
alter table weather_info add constraint FKn1ryb0fdikfthprqhrsof2x7r foreign key (tz_info_id) references weather_tz_info (id);
alter table weather_settings add constraint FKq5wch23lrpgn6u0n7yld8dawf foreign key (last_viewed_weather_city_id) references weather_city (id);
alter table weather_settings add constraint FKm1b783odx795vm09fv9gecf2w foreign key (notification_service_settings_id) references notification_service_settings (id);
alter table weather_settings add constraint FKmm4092k2cv3wka1ftijivbkdp foreign key (user_id) references users (id);
alter table weather_settings_cities add constraint FK1bpbofmuvis8usajsn2qv6wdj foreign key (cities_id) references weather_city (id);
alter table weather_settings_cities add constraint FKotg1ncwj41krxf7h73b7wdcgv foreign key (weather_settings_id) references weather_settings (id);
Hibernate: alter table weather_settings_viewed_cities add constraint FK5evnhootdtvlcn2tvg8c7v24s foreign key (viewed_cities_id) references weather_city (id);
Hibernate: alter table weather_settings_viewed_cities add constraint FKgxku0udvnb5kgqvmy7gnqhqr1 foreign key (weather_settings_id) references weather_settings (id);